#!/bin/bash

COMMAND="$1"
PROJECT_NAME="$2"

if [ "$COMMAND" = "init" ]; then
    if [ -z "$PROJECT_NAME" ]; then
        ENV_DIR="$(pwd)/.texbox"
    else
        ENV_DIR="$(pwd)/$PROJECT_NAME/.texbox"
        mkdir -p "$(pwd)/$PROJECT_NAME"
    fi

    mkdir -p "$ENV_DIR/texmf" "$ENV_DIR/var" "$ENV_DIR/config"

    cat > "$ENV_DIR/activate" << 'EOF'
# Save old environment variables
export _OLD_TEXBOX_PATH="$PATH"
export _OLD_TEXMFHOME="$TEXMFHOME"
export _OLD_TEXMFVAR="$TEXMFVAR"
export _OLD_TEXMFCONFIG="$TEXMFCONFIG"

deactivate() {
    export PATH="$_OLD_TEXBOX_PATH"
    export TEXMFHOME="$_OLD_TEXMFHOME"
    export TEXMFVAR="$_OLD_TEXMFVAR"
    export TEXMFCONFIG="$_OLD_TEXMFCONFIG"
    unset _OLD_TEXBOX_PATH _OLD_TEXMFHOME _OLD_TEXMFVAR _OLD_TEXMFCONFIG
    unset -f deactivate
    echo "TeXbox environment deactivated"
}

export TEXMFHOME="$(pwd)/.texbox/texmf"
export TEXMFVAR="$(pwd)/.texbox/var"
export TEXMFCONFIG="$(pwd)/.texbox/config"
export PATH="/usr/local/texlive/2025/bin/x86_64-linux:$PATH"

echo "TeXbox environment activated at $(pwd)/.texbox"
EOF

    echo "TeXbox environment initialized at $ENV_DIR"
fi